- n6001/hardware/ofs_n6001_usm/build/rtl/afu.sv
- n6001/hardware/ofs_n6001_usm/build/rtl/dc_bsp_pkg.sv
This change submits Doug's change he made in March for the USM CCB for the kernel to host mem path in order to fix the USM read bandwidth.
The change doubles not only the read response FIFO depth to 512, but also the command FIFO depth to 256 and command FIFO almost full threshold to 16.
The bandwidth changed as follows:
```
state | USM read+write | USM read | USM write
before | 29.63 GB/s | 17.99 GB/s | 24.65 GB/s
after | 44.56 GB/s | 27.21 GB/s | 24.62 GB/s
```
Test run so far:
- usm-bandwidth in a loop for 100 iterations
- simple_host_streaming in a loop for 100 iterations
- buffered_host_streaming in a loop for 100 iterations
- zero_copy_data_transfer in a loop for 100 iterations
- explicit_data_movement in a loop for 100 iterations
> changing the USM CCB for the kernel to host mem path

- d5005/README.md
- n6001/README.md
The example kernel compiler options was interpreted as a math formula. 
Updating it to indicate it is a command line instead.
> README example compiler statement cleanup

- common/source/host/mmd_dma.cpp
This change switches back to using double buffering which previously caused issues with the double_buffering and gzip designs.
The change was tested by running through
- 1000 iterations of double_buffering design
- 1000 iterations of gzip design with 500 MB input file
Requirement for this working is the updated FIM for N6001 with Quartus 23.2.
> remove mutex to allow for double buffering

- d5005/hardware/ofs_d5005/build/scripts/run.sh
- d5005/hardware/ofs_d5005_usm/build/scripts/run.sh
- d5005/scripts/build-bsp.sh
- n6001/hardware/ofs_n6001/build/scripts/run.sh
- n6001/hardware/ofs_n6001_usm/build/scripts/run.sh
- n6001/scripts/build-bsp.sh
To flexibly support all environments, the order of preference should be:
1) Explicit path if provided (a.k.a. stop trying to be "smart" and use
exactly what I'm asking, dagnabbit!)
2) $PATH search -- a set of installed OPAE .rpms should Just Work
and be usable *anywhere* the script runs.
3) If neither of these yield a working 'packager', fall back to a
bundled copy. This will only ever work in limited contexts such as an
HPC farm's local build of the product, and thus it should never take
priority over the either of the previous two selection paths.
> Improve selection of 'packager' utility

- common/source/host/mmd_device.cpp
- common/source/util/diagnostic/main.cpp
Fix for hsd 22018519029 - Remove fatal error when temperature not found on board if no BMC present. We don't want diagnose to fatally error out if it doesnt find temperature, just sau NA for temperature to let users know asp was not able to find temperature information, it might be because BMC is absent or some other reason
> Remove fatal error when temperature not found on board if no BMC present

- common/source/host/CMakeLists.txt
- common/source/host/mmd.cpp
- common/source/host/mmd_device.cpp
- common/source/host/mmd_device.h
- common/source/host/mmd_dma.cpp
- common/source/host/mmd_iopipes.cpp
- common/source/host/mmd_iopipes.h
- common/source/include/mmd.h
- common/source/util/diagnostic/main.cpp
- common/source/util/reprogram/reprogram.cpp
Added support for IO pipes in MMD software code, to satisfy LZ for 2023.2
Tested on agilex type of machines. 
Code should ideally work on stratix machines as well but not tested.
Testing
1) ASE testing using 1 and 4 pipes
2) Lab testing for 1 pipes currently with loopback within ASP , further testing in progress.
Tests
aocl diagnose
aocl program
openCL io pipe test
oneapi io streaming sample test - 
1 pipe  - https://github.com/pajgaonk/oneAPI-samples/tree/io_streaming_one_iopipe_test_update_2023.2
4 pipe (test in progress) - https://github.com/pajgaonk/oneAPI-samples/tree/io_streaming_multi_iopipes_test_update_2023.2
Currently loop back through HSSI using loopback cable in lab is not working and it might be timing related issue.
> Software enhancement for IO Pipes Support

- d5005/hardware/ofs_d5005/build/scripts/compile_script.tcl
- d5005/hardware/ofs_d5005_usm/build/scripts/compile_script.tcl
- d5005/scripts/setup-bsp.py
- n6001/hardware/ofs_n6001/build/scripts/compile_script.tcl
- n6001/hardware/ofs_n6001_iopipes/build/scripts/compile_script.tcl
- n6001/hardware/ofs_n6001_usm/build/scripts/compile_script.tcl
- n6001/hardware/ofs_n6001_usm_iopipes/build/scripts/compile_script.tcl
- n6001/scripts/setup-bsp.py
A recent change to the D5005 and N6001 OFS FIM hierarchy and build-structure broke the ASP build-flow. This is a work-around until we can find a more graceful way of managing it.
> Build hacks to work around recent FIM build-flow changes.

- n6001/hardware/ofs_n6001_iopipes/build/scripts/run.sh
- n6001/hardware/ofs_n6001_usm_iopipes/build/scripts/run.sh
updated PYTHONPATH in run.sh because it does work otherwise ,if we use 3*
> run.sh update for iopipes n6001 variants

- n6001/hardware/ofs_n6001/board_spec.xml
- n6001/hardware/ofs_n6001/build/afu_ip.qsf
- n6001/hardware/ofs_n6001/build/scripts/compile_script.tcl
- n6001/hardware/ofs_n6001/build/scripts/entry.tcl
- n6001/hardware/ofs_n6001/build/scripts/run.sh
- n6001/hardware/ofs_n6001_iopipes/board_spec.xml
- n6001/hardware/ofs_n6001_iopipes/build/afu_ip.qsf
- n6001/hardware/ofs_n6001_iopipes/build/scripts/compile_script.tcl
- n6001/hardware/ofs_n6001_iopipes/build/scripts/entry.tcl
- n6001/hardware/ofs_n6001_iopipes/build/scripts/run.sh
- n6001/hardware/ofs_n6001_usm/board_spec.xml
- n6001/hardware/ofs_n6001_usm/build/afu_ip.qsf
- n6001/hardware/ofs_n6001_usm/build/scripts/compile_script.tcl
- n6001/hardware/ofs_n6001_usm/build/scripts/entry.tcl
- n6001/hardware/ofs_n6001_usm/build/scripts/run.sh
- n6001/hardware/ofs_n6001_usm_iopipes/board_spec.xml
- n6001/hardware/ofs_n6001_usm_iopipes/build/afu_ip.qsf
- n6001/hardware/ofs_n6001_usm_iopipes/build/scripts/compile_script.tcl
- n6001/hardware/ofs_n6001_usm_iopipes/build/scripts/entry.tcl
- n6001/hardware/ofs_n6001_usm_iopipes/build/scripts/run.sh
- n6001/scripts/setup-bsp.py
Due to some recent changes in the FIM repo (additional hierarchy of board/{target}/ to the syn/syn_top path broke the ASP setup and build flows. This commit should clean it up and be more adaptable in the future.
OneAPI kernel compilation still occurs at the hardware/{variant}/ location, while the Quartus build now occurs in {tmp|hardware}/{variant}/fim_platform/build/syn/board/{FIM variant}/syn_top.
> N6001: Update build-flow to match recent FIM changes

- n6001/scripts/create-tarball.sh
The original script would prepend oneapi-asp-b6001/ to the symlink paths, which would make them unusable later. This change simplifies the tar process and looks to work better (symlinks at kernel-build location and Quartus-build location look good).
> N6001: Update create-tarball script to handle symlinks

- common/source/host/mmd_device.cpp
If BMC is missing we saw bug where code crashes because we try to destroy object which is never created because of missing BMC in system.
Fixed the bug , tested on f dev kit in SJ minicloud
> bmc missing , aocl diagnose temperature reporting fix 

- fseries_dk/scripts/setup-bsp.py
- n6001/scripts/setup-bsp.py
The afu-synth-setup command in setup_bsp was passed an absolute path for filelist.txt. This absolute path was embedded in the output of afu-synth-setup, which makes the files not portable. This change removes that absolute path.
> N6001: remove abs path from setup_bsp

- d5005/hardware/ofs_d5005/build/scripts/run.sh
- d5005/hardware/ofs_d5005_usm/build/scripts/run.sh
- n6001/hardware/ofs_n6001/build/scripts/run.sh
- n6001/hardware/ofs_n6001_iopipes/build/scripts/run.sh
- n6001/hardware/ofs_n6001_usm/build/scripts/run.sh
- n6001/hardware/ofs_n6001_usm_iopipes/build/scripts/run.sh
We previously hard-coded the path to the packager, which included a Python version. This change will try to find the installation and set PYTHONPATH appropriately.
> Clean up PYTHONPATH and packager handling

- d5005/hardware/ofs_d5005/build/scripts/adjust_plls.tcl
- d5005/hardware/ofs_d5005_usm/build/scripts/adjust_plls.tcl
- n6001/hardware/ofs_n6001/build/scripts/adjust_plls.tcl
- n6001/hardware/ofs_n6001_iopipes/build/scripts/adjust_plls.tcl
- n6001/hardware/ofs_n6001_usm/build/scripts/adjust_plls.tcl
- n6001/hardware/ofs_n6001_usm_iopipes/build/scripts/adjust_plls.tcl
This was a fix suggested by SSE for devices with more than 1M ALUTs. The tcl script does a bit of manipulation of the ALUT numbers which requires them to not have commas, so this change removes all commas from the string returned from get_fitter_resource_usage. N6001 compilation completed without issue (granted, it doesn't have 1M+ ALUTs but at least it didn't break the current build).
> Fix the adjust-plls script to accept devices with more than 1M ALUTs

- n6001/hardware/ofs_n6001/build/opencl_bsp.sdc
- n6001/hardware/ofs_n6001/build/scripts/adjust_plls.tcl
- n6001/hardware/ofs_n6001/build/user_clock.sdc
- n6001/hardware/ofs_n6001_iopipes/build/opencl_bsp.sdc
- n6001/hardware/ofs_n6001_iopipes/build/scripts/adjust_plls.tcl
- n6001/hardware/ofs_n6001_iopipes/build/user_clock.sdc
- n6001/hardware/ofs_n6001_usm/build/opencl_bsp.sdc
- n6001/hardware/ofs_n6001_usm/build/scripts/adjust_plls.tcl
- n6001/hardware/ofs_n6001_usm/build/user_clock.sdc
- n6001/hardware/ofs_n6001_usm_iopipes/build/opencl_bsp.sdc
- n6001/hardware/ofs_n6001_usm_iopipes/build/scripts/adjust_plls.tcl
- n6001/hardware/ofs_n6001_usm_iopipes/build/user_clock.sdc
A recent FIM change altered the hierarchy of the user/kernel clock, causing adjust_plls.tcl (and associated kernel-clock timing constraints) to fail. This work-around fixes takes that hierarchy change into account. A proper future fix should leverage the scripts within ofs_partial_reconfig from the FIM.
> N6001: adapt to FIM's kernel-clock hierarchy name change

- d5005/scripts/create-tarball.sh
- fseries_dk/scripts/create-tarball.sh
- n6001/scripts/create-tarball.sh
After removing the transform option to the tar command we lost the forced-hierarchy. This should get the proper hierarchy back.
> Update create-tarball scripts to retain hierarchy

- fseries_dk/hardware/fseries_dk/build/opencl_bsp.sdc
- fseries_dk/hardware/fseries_dk/build/scripts/adjust_plls.tcl
- fseries_dk/hardware/fseries_dk/build/user_clock.sdc
- fseries_dk/hardware/fseries_dk_iopipes/build/opencl_bsp.sdc
- fseries_dk/hardware/fseries_dk_iopipes/build/scripts/adjust_plls.tcl
- fseries_dk/hardware/fseries_dk_iopipes/build/user_clock.sdc
- fseries_dk/hardware/fseries_dk_usm/build/opencl_bsp.sdc
- fseries_dk/hardware/fseries_dk_usm/build/scripts/adjust_plls.tcl
- fseries_dk/hardware/fseries_dk_usm/build/user_clock.sdc
- fseries_dk/hardware/fseries_dk_usm_iopipes/build/opencl_bsp.sdc
- fseries_dk/hardware/fseries_dk_usm_iopipes/build/scripts/adjust_plls.tcl
- fseries_dk/hardware/fseries_dk_usm_iopipes/build/user_clock.sdc
A recent FIM change altered the hierarchy of the user/kernel clock, causing adjust_plls.tcl (and associated kernel-clock timing constraints) to fail. This work-around fixes takes that hierarchy change into account. A proper future fix should leverage the scripts within ofs_partial_reconfig from the FIM.
> fseries-dk: adapt to FIM's kernel-clock hierarchy name change

- d5005/hardware/ofs_d5005/build/scripts/adjust_plls.tcl
- d5005/hardware/ofs_d5005/build/scripts/run.sh
- d5005/hardware/ofs_d5005_usm/build/scripts/adjust_plls.tcl
- d5005/hardware/ofs_d5005_usm/build/scripts/run.sh
- d5005/scripts/create-tarball.sh
- n6001/hardware/ofs_n6001/build/scripts/adjust_plls.tcl
- n6001/hardware/ofs_n6001/build/scripts/run.sh
- n6001/hardware/ofs_n6001_iopipes/build/scripts/adjust_plls.tcl
- n6001/hardware/ofs_n6001_iopipes/build/scripts/run.sh
- n6001/hardware/ofs_n6001_usm/build/scripts/adjust_plls.tcl
- n6001/hardware/ofs_n6001_usm/build/scripts/run.sh
- n6001/hardware/ofs_n6001_usm_iopipes/build/scripts/adjust_plls.tcl
- n6001/hardware/ofs_n6001_usm_iopipes/build/scripts/run.sh
- n6001/scripts/create-tarball.sh
- remove the expectation in run.sh for the local PYTHONPATH to be 3.8.
- add support in adjust-plls.tcl for devices with 1M+ ALUTs.
- clean up create-tarball.sh scripts for symlinks and folder hierarchy.
> Merge in useful changes from master

- d5005/scripts/build-default-aocx.sh
- d5005/scripts/create-tarball.sh
- n6001/scripts/build-default-aocx.sh
- n6001/scripts/create-tarball.sh
Recent changes to FIM file handling has led to changes needed by the build-default-aocxs and create-tarball scripts. This will also be needed on release/ofs-2023.2 branch.
Addresses #/14020142236
> Update build-default-aocx and create-tarball scripts

- n6001/hardware/ofs_n6001_usm/build/bsp_design_files.tcl
- n6001/hardware/ofs_n6001_usm/build/rtl/avmm_single_burst_partial_writes.v
- n6001/hardware/ofs_n6001_usm/build/rtl/kernel_wrapper.v
- n6001/hardware/ofs_n6001_usm_iopipes/build/bsp_design_files.tcl
- n6001/hardware/ofs_n6001_usm_iopipes/build/rtl/avmm_single_burst_partial_writes.v
- n6001/hardware/ofs_n6001_usm_iopipes/build/rtl/kernel_wrapper.v
Rather than clutter kernel-wrapper with the logic to handle USM burst-splitting, move it into a separate block.
> Move AVMM write-burst-splitting logic into own module

- d5005/hardware/ofs_d5005/board_spec.xml
- d5005/hardware/ofs_d5005_usm/board_spec.xml
- n6001/hardware/ofs_n6001/board_spec.xml
- n6001/hardware/ofs_n6001_iopipes/board_spec.xml
- n6001/hardware/ofs_n6001_usm/board_spec.xml
- n6001/hardware/ofs_n6001_usm_iopipes/board_spec.xml
Validation: ofs_n6001 board_test build generated a .fpga file.
> Fix host/agent terminology in board_spec.xml

- d5005/scripts/build-default-aocx.sh
- n6001/scripts/build-default-aocx.sh
Add support for building all of the variants (serially) instead of requiring user intervention for each one. The default will build all of them, or you can choose one at a time.
This is particularly useful for n6001 with 4 different hardware variants.
> Cleanup of build-default-aocx scripts

- d5005/scripts/build-default-aocx.sh
- n6001/scripts/build-default-aocx.sh
Add support for building all of the variants (serially) instead of requiring user intervention for each one. The default will build all of them, or you can choose one at a time. 
This is particularly useful for n6001 with 4 different hardware variants.
> Further cleanup of build-default-aocx scripts

- d5005/scripts/setup-bsp.py
- n6001/scripts/setup-bsp.py
The pr-build-template folder is huge, but we really only need/want the blue_bits subfolder (~45MB) which contains the FIM's programming files. I'm leaving the pr-build-template copy in for now, but will eventually remove it and we'll be left with just the blue_bits folder in each variant. This allows different variants to use different FIMs.
Ran build-bsp.sh multiple times in the same place - the blue_bits folder get replaced each time the command is executed.
> Preserve the FIM programming files in each variant folder

- common/source/host/mmd_iopipes.cpp
Removed default prints for iopipes, those prints/debug messages can be enabled by setting env variable MMD_ENABLE_DEBUG.
No functional changes.
MMD compile passing.
> Moved comments such that they can be enabled by debug env variables 

- common/source/host/mmd_device.cpp
- common/source/host/mmd_iopipes.cpp
Removed default prints for iopipes, those prints/debug messages can be enabled by setting env variable MMD_ENABLE_DEBUG.
No functional changes.
MMD compile passing.
> Moved comments such that they can be enabled by debug env variables (missed some in previous merge)

- d5005/scripts/build-default-aocx.sh
- n6001/scripts/build-default-aocx.sh
Fix a typo in the build-default-aocx.sh scripts for both n6001 and d5005 platforms. The script ran fine on my test systems, but failed during validation tests.
> Fix - build-default-aocx.sh typos

- d5005/scripts/build-default-aocx.sh
- n6001/scripts/build-default-aocx.sh
Fix a typo in the buid-default-aocx.sh scripts for both d5005 and n6001 platforms. Error is only seen with some versions of bash.
> Fix typo in build-default-aocx.sh scripts

- fseries_dk/hardware/fseries_dk/build/opencl_bsp.sdc
- fseries_dk/hardware/fseries_dk_iopipes/build/opencl_bsp.sdc
- fseries_dk/hardware/fseries_dk_usm/build/opencl_bsp.sdc
- fseries_dk/hardware/fseries_dk_usm_iopipes/build/opencl_bsp.sdc
- n6001/hardware/ofs_n6001/build/opencl_bsp.sdc
- n6001/hardware/ofs_n6001_iopipes/build/opencl_bsp.sdc
- n6001/hardware/ofs_n6001_usm/build/opencl_bsp.sdc
- n6001/hardware/ofs_n6001_usm_iopipes/build/opencl_bsp.sdc
The current n6001 master branch has problems with timing due to a hierarchy change in the memory-subsystems leading to an invalid clock-group assignment. This leads to recovery violations that can't be fixed by reducing the kernel-clock frequencies, and the kernel-clock being incorrectly reduced to a useless frequency.
Manually modified the opencl_bsp.sdc file in-place using the Timing Analyzer GUI for a qri build that had timing violations, and all of the violations disappeared (they were all on CDC paths).
> [Fix] memory-clock clock-group hierarchy assignments

- d5005/scripts/setup-bsp.py
- n6001/scripts/setup-bsp.py
Recent d5005 setup script changes incorrectly set the n6001 FIM qpf filename. This should fix that typo.
Clean clone, setup, and build opencl+oneapi designs.
> [Fix] setup script cleanup and fix

- n6001/hardware/ofs_n6001/build/scripts/run.sh
- n6001/hardware/ofs_n6001_iopipes/build/scripts/run.sh
- n6001/hardware/ofs_n6001_usm/build/scripts/run.sh
- n6001/hardware/ofs_n6001_usm_iopipes/build/scripts/run.sh
Add error codes when exiting from the run.sh build script. Without error codes a .fpga file will still be generated even though it doesn't contain any gbs data.
Compiled crr (known to not fit on N6001) and no .fpga file was generated.
> [Update] Add error codes to run.sh exits

- d5005/hardware/ofs_d5005/build/bsp_design_files.tcl
- d5005/hardware/ofs_d5005/build/rtl/avmm_single_burst_partial_writes.v
- d5005/hardware/ofs_d5005/build/rtl/avmm_wr_ack_burst_to_word.sv
- d5005/hardware/ofs_d5005/build/rtl/avmm_wr_ack_gen.sv
- d5005/hardware/ofs_d5005/build/rtl/avmm_wr_ack_tracker.sv
- d5005/hardware/ofs_d5005/build/rtl/kernel_wrapper.v
- d5005/hardware/ofs_d5005/quartus.ini
- d5005/hardware/ofs_d5005_usm/build/bsp_design_files.tcl
- d5005/hardware/ofs_d5005_usm/build/rtl/avmm_single_burst_partial_writes.v
- d5005/hardware/ofs_d5005_usm/build/rtl/avmm_wr_ack_burst_to_word.sv
- d5005/hardware/ofs_d5005_usm/build/rtl/avmm_wr_ack_gen.sv
- d5005/hardware/ofs_d5005_usm/build/rtl/avmm_wr_ack_tracker.sv
- d5005/hardware/ofs_d5005_usm/build/rtl/kernel_wrapper.v
- d5005/hardware/ofs_d5005_usm/quartus.ini
- n6001/hardware/ofs_n6001/build/bsp_design_files.tcl
- n6001/hardware/ofs_n6001/build/rtl/avmm_single_burst_partial_writes.v
- n6001/hardware/ofs_n6001/build/rtl/kernel_wrapper.v
- n6001/hardware/ofs_n6001/quartus.ini
- n6001/hardware/ofs_n6001_iopipes/build/bsp_design_files.tcl
- n6001/hardware/ofs_n6001_iopipes/build/rtl/avmm_single_burst_partial_writes.v
- n6001/hardware/ofs_n6001_iopipes/build/rtl/kernel_wrapper.v
- n6001/hardware/ofs_n6001_iopipes/quartus.ini
- n6001/hardware/ofs_n6001_usm/build/rtl/kernel_wrapper.v
- n6001/hardware/ofs_n6001_usm/quartus.ini
- n6001/hardware/ofs_n6001_usm_iopipes/build/rtl/kernel_wrapper.v
- n6001/hardware/ofs_n6001_usm_iopipes/quartus.ini
Previously all kernel_wrapper.v files for all ASPs (D5005 and N6001) as well as the board variants (ofs_d5005, ofs_d5005_usm...) were different. This change commonizes all board variant's kernel_wrapper.v files.
Additionally all quartus.ini files were removed as they are obsolete now.
none
none
- compiled and ran board_test and simple_host_streaming on D5005 (targeting ofs_d5005 and ofs_d5005_usm respectively) -> passed
- compiled and ran board_test and simple_host_streaming on N6001 using slimFIM (targeting ofs_n6001 and ofs_n6001_usm respectively) -> passed
- compiled and ran the following designs on N6001 using base FIM (all passed):
anr
board_test
cholesky
cholesky_inversion
db
decompress
double_buffering
mvdr_beamforming
qri
simple_host_streaming
buffered_host_streaming …
> [Update] commonizing all kernel_wrapper.v files for d5005 and n6001

- d5005/hardware/ofs_d5005/build/board.qsys
- d5005/hardware/ofs_d5005/build/ddr_board.qsys
- d5005/hardware/ofs_d5005/build/ddr_channel.qsys
- d5005/hardware/ofs_d5005/build/ip/ddr_board/ddr4_pipe_to_bankdiv.ip
- d5005/hardware/ofs_d5005/build/ip/ddr_board/ddr4_pipe_to_kernel.ip
- d5005/hardware/ofs_d5005/build/ip/ddr_board/ddr4emif_pipe_0.ip
- d5005/hardware/ofs_d5005/build/make_ipx.sh
- n6001/hardware/ofs_n6001/build/ip/board/board_kernel_clk_export.ip
- n6001/hardware/ofs_n6001/build/ip/board/board_kernel_interface.ip
- n6001/hardware/ofs_n6001/build/make_ipx.sh
- n6001/hardware/ofs_n6001/build/opencl_bsp.sdc
- n6001/hardware/ofs_n6001/build/rtl/dma/dma.vh
- n6001/hardware/ofs_n6001_iopipes/build/opencl_bsp.sdc
- n6001/hardware/ofs_n6001_usm/build/ip/board/board_kernel_clk_export.ip
Commonizing more files between board variants of D5005 and N6001
This change makes more files common between the D5005 and N6001 ASPs as well as between board variants.
It cleans up differences between the ofs_d5005 and ofs_d5005_usm .qsys and .ip files, cleans up differences to the make_ipx.sh files as well as opencl_bsp.sdc file differences in the N6001 ASPs.
none
none
- compiled and ran the following designs in HW on N6001:
ofs_n6001:
anr
board_test
cholesky
cholesky_inversion
db
decompress
merge_sort
qri
ofs_n6001_usm:
simple_host_streaming
buffered_host_streaming
explicit_data_movement
zero_copy_data_transfer
- compiled and ran the following designs in HW on D5005:
ofs_d5005:
anr
board_test
cholesky
cholesky_inversion
db
decompress
double_buffering
gzip
merge_sort
qrd
qri …
> [Update] more cleanup between D5005 and N6001 board variants

- d5005/ase/compile-kernel.sh
- n6001/ase/compile-kernel.sh
------------- *Keep everything below this line* -------------------------
With updates to the aclsycl tool for 2024.0 we don't need the -no-env-check argument anymore.
ASE zero-copy-data-transfer passed for D5005 and N6001 platforms.
> [Update] Remove -no-env-check from ASE scripts

- d5005/scripts/build-bsp.sh
- d5005/scripts/setup-bsp.py
- n6001/scripts/build-bsp.sh
- n6001/scripts/setup-bsp.py
Customer-request to improve build-bsp and setup-bsp messaging - tell the user that the script(s) completed successfully. Currently, the final outputs to the terminal are the outputs from running afu-synth-setup, which isn't particularly useful.
None.
Ran build-bsp for n6001 and d5005 platforms.
> [Update] Improve script messaging/status

- n6001/.gitignore
- n6001/hardware/ofs_n6001/build/quartus.ini
- n6001/hardware/ofs_n6001_iopipes/build/quartus.ini
- n6001/hardware/ofs_n6001_usm/build/quartus.ini
- n6001/hardware/ofs_n6001_usm_iopipes/build/quartus.ini
We see some rare 'routing preservation failure' Internal Errors when compiling the IO-Pipes design (there shouldn't be anything specific to the IO-Pipes variants). This ini helps reduce the frequency of the IEs.
None
Compiled the normal suite of OneAPI-samples designs, observed the quartus.ini file is included in quartus_sh_compile.log.
> [Update] Add ini to work around Quartus 'routing preservation' Internal Errors

- d5005/linux64/libexec/setup_permissions.sh
- n6001/linux64/libexec/setup_permissions.sh
Fixed a simple typo. No functional changes.
None.
> [Update] Fix a typo in the messages printed in setup_permissions.sh

- d5005/hardware/ofs_d5005/build/rtl/bsp_logic.sv
- d5005/hardware/ofs_d5005/build/rtl/kernel_wrapper.v
- d5005/hardware/ofs_d5005/build/rtl/ofs_asp.vh
- d5005/hardware/ofs_d5005/build/rtl/ofs_asp_pkg.sv
- d5005/hardware/ofs_d5005_usm/build/rtl/bsp_logic.sv
- d5005/hardware/ofs_d5005_usm/build/rtl/kernel_wrapper.v
- d5005/hardware/ofs_d5005_usm/build/rtl/ofs_asp.vh
- d5005/hardware/ofs_d5005_usm/build/rtl/ofs_asp_pkg.sv
The previous PR to leverage more FIM defines/parameters didn't work for the D5005 platform. This change reverts the D5005 platform to an earlier state.
Compilation of some oneapi kernels, a few minutes into synthesis (past where the failures previously occurred).
> [Fix] Revert recent D5005 changes 

- d5005/scripts/setup-bsp.py
- n6001/scripts/setup-bsp.py
This change adds some intelligence to the setup-bsp.py script to find the appropriate qpf and qsf files from the pr-build-template folder and symlink them where the OneAPI build-flow expects them to be. Previously these files were hardcoded depending on whether the platform was d5005 or n6001, but that wasn't helpful when porting FIMs. This should simplify porting the ASP to different platforms (as long as the filenames are somewhat consistent).
Ran build-bsp.py for both n6001 and d5005, and then successfully compiled many oneapi-samples designs.
> [Update] Commonize setup-bsp.py to find default qpf and qsf files

- common/source/util/diagnostic/main.cpp
*Describe the issue, update, change or fix and **why***
HSD 14020208380. Added peak reference speed for PCIe Gen4 for users reference and updated peak speeds for PCIe Gen3.
> [Update] : HSD 14020208380, fixed PCIe Gen3 reference peak speed and added one for PCIe Gen4

- fseries-dk/hardware/ofs_fseries-dk/board_spec.xml
- fseries-dk/hardware/ofs_fseries-dk/build/board_hw.tcl
- fseries-dk/hardware/ofs_fseries-dk_usm/board_spec.xml
- fseries-dk/hardware/ofs_fseries-dk_usm/build/board_hw.tcl
The default FIM for fseries-dk provides 2 channels of DDR memory. This PR changes the default number of channels in the ASP from 4 to 2.
None
Host crashes following an unsuccessful PR (aocl initialize acl0 mydesign.fpga). So, the fseries-dk platform needs to be debugged.
> [Update] - modify the fseries-dk platform to 2 channels of DDR

- fseries-dk/hardware/common/build/rtl/ofs_asp_pkg.sv
- fseries-dk/hardware/ofs_fseries-dk/build/rtl/ofs_asp.vh
- fseries-dk/hardware/ofs_fseries-dk_usm/build/rtl/ofs_asp.vh
- iseries-dk/hardware/common/build/rtl/ofs_asp_pkg.sv
- iseries-dk/hardware/ofs_iseries-dk/build/rtl/ofs_asp.vh
- iseries-dk/hardware/ofs_iseries-dk_usm/build/rtl/ofs_asp.vh
- n6001/hardware/common/build/rtl/ofs_asp_pkg.sv
- n6001/hardware/ofs_n6001/build/rtl/ofs_asp.vh
- n6001/hardware/ofs_n6001_iopipes/build/rtl/ofs_asp.vh
- n6001/hardware/ofs_n6001_usm/build/rtl/ofs_asp.vh
- n6001/hardware/ofs_n6001_usm_iopipes/build/rtl/ofs_asp.vh
A recent change to the header files used in the FIM broke ASP builds. ASP was explicitly including specific vh files, as well as explicit defines from them. This change leverages the single FIM vh file that already `includes the necessarily vh files. We will need to find a better way to access the `define assignments, though - preferably something within the PIM's pkg/vh files since those should abstract the details away from the ASP while retaining the same names.
Compilation of n6001 sample designs using nightly base FIM (5pf/3vf) have all progressed further than the nightly builds did.
> [Fix]- Update n6001/iseries/fseries header assignments

- fseries-dk/hardware/ofs_fseries-dk/build/rtl/ofs_asp.vh
- fseries-dk/hardware/ofs_fseries-dk_usm/build/rtl/ofs_asp.vh
- iseries-dk/hardware/ofs_iseries-dk/build/rtl/ofs_asp.vh
- iseries-dk/hardware/ofs_iseries-dk_usm/build/rtl/ofs_asp.vh
- n6001/hardware/ofs_n6001_iopipes/build/rtl/ofs_asp.vh
- n6001/hardware/ofs_n6001_usm/build/rtl/ofs_asp.vh
- n6001/hardware/ofs_n6001_usm_iopipes/build/rtl/ofs_asp.vh
A recent change to the FIM's defines caused the local-memory defines in the ASP to be mishandled. This will hopefully go away with the move to qprs/ip files, but this is a fix for the rest of the Agilex variants for now. I accidentally only fixed one of the vh files with my earlier commit, while the rest of the vh files were only partially fixed (I moved the bug around instead of resolving it for those incomplete changes). I noticed this while using ASE with iseries-dk and the memory-interfaces in board.sv were weird.
Compilation of a few designs for each variant. Opening the database in the Quartus GUI shows me that the ddr_board and ddr_channel IPs consume resources, whereas without the change those IPs were either missing or tiny. Also, the build-time increased drastically (it doesn't …
> *[Fix]- Update header files to match changes to FIM

- fseries-dk/hardware/ofs_fseries-dk/build/rtl/ofs_asp.vh
- fseries-dk/hardware/ofs_fseries-dk_usm/build/rtl/ofs_asp.vh
- iseries-dk/hardware/ofs_iseries-dk/build/rtl/ofs_asp.vh
- iseries-dk/hardware/ofs_iseries-dk_usm/build/rtl/ofs_asp.vh
- n6001/hardware/ofs_n6001/build/rtl/ofs_asp.vh
- n6001/hardware/ofs_n6001_iopipes/build/rtl/ofs_asp.vh
- n6001/hardware/ofs_n6001_usm/build/rtl/ofs_asp.vh
- n6001/hardware/ofs_n6001_usm_iopipes/build/rtl/ofs_asp.vh
In earlier commits a typo was made for the assignment of the local-memory channel 2 interface. This should remedy that typo.
None
Visual review, ASE compilation and debugging of a different change.
> *[Fix]- Fix typo in memory-interface defines for Agilex-based platforms

- common/hardware/common/build/rtl/kernel_wrapper.v
Fix an assignment bug in the kernel-wrapper where the USM[1] address was connected to the wrong wires. Clean up whitespace and unused code/comments in kernel-wrapper, too.
n/a
> *[Fix]- Fix USM address connection bug in kernel-wrapper*

- common/hardware/common/build/rtl/kernel_wrapper.v
There is a bug in kernel-wrapper when no USM channels are included in the ASP, yet the ASP was still trying to tie-off signals that didn't exist.
None
Compiled shs, bhs, zcdt, edm for D5005 platform.
> *[Fix]- Fix a bug in USM tie-off handling*

- common/hardware/common/build/rtl/ofs_plat_afu.sv
The host-channel tie-off parameter was accidentally included in a previous PR. For single-link the value should simply remain 'b1. For multiple links it needs to be changed to match the aggregated VF channels.
> *[Fix]- Fix the tie-off assignment parameter for host-channels

- fseries-dk/hardware/common/build/ofs_asp.sdc
- iseries-dk/hardware/common/build/ofs_asp.sdc
- n6001/hardware/common/build/ofs_asp.sdc
The original SDC assignments for the EMIF clocks were wrong and led to timing violations in the analyses because the clock domains weren't set to be asynchronous.
none
ran board_test compile for n6001, iseries-dk and fseries-dk ASPs
> fix paths for EMIF clocks

- d5005/hardware/ofs_d5005/board_spec.xml
- d5005/hardware/ofs_d5005_usm/board_spec.xml
- fseries-dk/hardware/ofs_fseries-dk/board_spec.xml
- fseries-dk/hardware/ofs_fseries-dk_usm/board_spec.xml
- iseries-dk/hardware/ofs_iseries-dk/board_spec.xml
- iseries-dk/hardware/ofs_iseries-dk_usm/board_spec.xml
- n6001/hardware/ofs_n6001/board_spec.xml
- n6001/hardware/ofs_n6001_iopipes/board_spec.xml
- n6001/hardware/ofs_n6001_usm/board_spec.xml
- n6001/hardware/ofs_n6001_usm_iopipes/board_spec.xml
The version field in board_spec.xml should match the required Quartus version to be used for compilation. It was updated to 24.1 for the 2024.2 ASP release for n6001, iseries-dk and fseries-dk and for 23.4 for d5005 as this FIM is still using Quartus 23.4.
none
none
compile test for n6001, iseries-dk, fseries-dk and d5005
> update board_spec.xml version with Quartus version needed from FIMs

- common/hardware/common/build/rtl/avmm_wr_ack_gen.sv
Earlier versions of Quartus didn't complain, but this asynchronous reset coding is incorrect and should be fixed.
The syntax for this register's async reset is wrong and the latest version of Quartus complains about it.
None
Compiled using Quartus 24.3/175 (matching the recent FIM version).
> *[Fix] async reset syntax bug*

- common/ase/compile-kernel.sh
- common/ase/setup.sh
- common/ase/simulate-aocx.sh
Most recent versions of ACDS, sycl, and OPAE require a few changes to support ASE.
none
none
zero-copy-data-transfer kernel with n6001 usm variant. Test hangs, but at least it compiles. Debugging possible compiler bug since the ASP hasn't really changed and the runtime polls the kernel's status forever.
> [Update] Updates to ASE for latest Quartus and sycl compiler versions

- fseries-dk/hardware/ofs_fseries-dk/build/rtl/ofs_asp.vh
- fseries-dk/hardware/ofs_fseries-dk_usm/build/rtl/ofs_asp.vh
- iseries-dk/hardware/ofs_iseries-dk/build/rtl/ofs_asp.vh
- iseries-dk/hardware/ofs_iseries-dk_usm/build/rtl/ofs_asp.vh
- n6001/hardware/ofs_n6001/build/rtl/ofs_asp.vh
- n6001/hardware/ofs_n6001_iopipes/build/rtl/ofs_asp.vh
- n6001/hardware/ofs_n6001_usm/build/rtl/ofs_asp.vh
- n6001/hardware/ofs_n6001_usm_iopipes/build/rtl/ofs_asp.vh
- oneapi_asp_editor/oneapi_asp_editor_hw.tcl
The write-ack `defines are not being handled properly - this commit should fix them for the platforms that require write-acks (where the FIM uses AXI rather than AVMM).
In ASE I can see the kernel-system make a write-request that never gets ack'd/completed.
None
- [N] Document Update Required? (Specify FIM/AFU/Scripts)
none
boardtest 'launch kernel' test in ASE - hangs without the change, passes with it.
> [Fix] Update write-ack definitions

- common/scripts/build-opae.sh
Update the scripts to use opae-sim's master branch by default.
ASE boardtest and zcdt.
> [Update] build-opae.sh to use latest opae-sim
